server:
  port: 3333   
     
spring:
  profiles:
    active: swagger
    
    
    
---
spring:
  profiles: prod

  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 2000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
